resolver: lts-5.14
# docker:
#   enable: true
#   repo: fpco/stack-full
packages:
  - "."
  - location:
      git: https://github.com/commercialhaskell/stack.git
      commit: master
    extra-dep: true
extra-deps:
- hpack-0.10.0
- path-0.5.7
- path-io-1.1.0
ghc-options:
  "*": -Wall
