resolver: nightly-2016-04-20
packages:
  - "."
  - location:
      git: https://github.com/commercialhaskell/stack.git
      commit: e0713a557ae5231557504d82462e1c507847fc45
    extra-dep: true
extra-deps:
- hpack-0.10.0
- path-0.5.7
- path-io-1.1.0
ghc-options:
  "*": -Wall
